#!/bin/bash
SECONDS=0

if (($# != 3))
  then
    echo "Wrong number of arguments"
    exit 1
fi

n=$1;
k=$2;
k2=$3;

if ! parametersCheck $n n
then 
    exit 1
fi

if ! parametersCheck $k k
then 
    exit 1
fi

if (($k >= $n))
  then
    echo "k can't be higher than n"
    exit 1
fi

if ! parametersCheck $k2 k_1
then 
    exit 1
fi

GenReg $n $k -e -a stdout | kostryBiregularne $n $k $k2;

subor=${n}_${k}_3.erg;

if ((n < 10))
then
    subor=0${n}_${k}_3.erg
fi

cat $subor >> maxMinBireg${k}-${n}-${k2}.txt;
rm $subor;

echo "trvanie celeho spracovania je $SECONDS sekund" >> maxMinBireg${k}-${n}-${k2}.txt
echo "trvanie celeho spracovania je $SECONDS sekund";
exit 0;
