#!/bin/bash
SECONDS=0

if (($# != 4))
  then
    echo "Wrong number of arguments"
    exit 1
fi

pocetCasti=$1;
n=$2;
k=$3;
k2=$4;

if ! parametersCheck $pocetCasti j
then 
    exit 1
fi

if ! parametersCheck $n n
then 
    exit 1
fi

if ! parametersCheck $k k
then 
    exit 1
fi

if (($k >= $n))
  then
    echo "k can't be higher than n"
    exit 1
fi

if ! parametersCheck $k2 k_1
then 
    exit 1
fi

for i in $(eval echo {1..${pocetCasti}}); do
  GenReg $n $k -e -a stdout -m $i $pocetCasti | kostryBiregularne out-graf-$i $n $k $k2 &
done

wait;
zberBiregularne out-graf $pocetCasti $n $k $k2;

eval rm out-graf-{1..${pocetCasti}};

for i in $(eval echo {1..${pocetCasti}}); do
  subor=${n}_${k}_3#${i}.erg

  if ((n < 10))
  then
    subor=0${n}_${k}_3.erg
  fi

  cat $subor >> maxMinBireg${k}-${n}-${k2}-${pocetCasti}.txt
  rm $subor
done

echo "trvanie celeho spracovania je $SECONDS sekund" >> maxMinBireg${k}-${n}-${k2}-${pocetCasti}.txt
echo "trvanie celeho spracovania je $SECONDS sekund";
exit 0;