#!/bin/bash
SECONDS=0

pocetCasti=$1;
n=$2;
k=$3;
k2=$4

for i in $(eval echo {1..${pocetCasti}}); do
  mkfifo graf-$i
  mkfifo out-graf-$i
  GenReg $n $k -e -a stdout -m $i $pocetCasti > graf-$i & 
  biregSubor graf-$i $n $k $k2 &
done

zberBireg out-graf $pocetCasti $n $k $k2;
#wait;

eval rm graf-{1..${pocetCasti}};

#paralelneKostry out-graf $n $k $pocetCasti;
#./build/bin/pocitanieKostier out-graf $n $k $pocetCasti;

eval rm out-graf-{1..${pocetCasti}};

for i in $(eval echo {1..${pocetCasti}}); do
  subor=${n}_${k}_3#${i}.erg
  cat $subor >> maxMinBireg${k}-${n}-${k2}-${pocetCasti}.txt
  rm $subor
done

echo "trvanie celeho spracovania je $SECONDS sekund" >> maxMinBireg${k}-${n}-${k2}-${pocetCasti}.txt
echo "trvanie celeho spracovania je $SECONDS sekund";
exit 0;