#!/bin/bash
SECONDS=0

pocetCasti=$1;
n=$2;
k=$3;
skupina=$4

for i in $(eval echo {1..${pocetCasti}}); do
  mkfifo graf-$i
  mkfifo out-graf-$i
  mkfifo generator-$i
  GenReg $n $k -e -a stdout -m $i $pocetCasti > generator-$i & 
  regSerialSubor graf-$i $n $k &
  #./build/bin/pocitanieKostier graf-$i $n $k &
done

rozdelovac generator graf $pocetCasti $n $skupina &
zber out-graf $pocetCasti $n $k;

eval rm graf-{1..${pocetCasti}};


eval rm out-graf-{1..${pocetCasti}};
eval rm generator-{1..${pocetCasti}};

for i in $(eval echo {1..${pocetCasti}}); do
  subor=${n}_${k}_3#${i}.erg
  cat $subor >> maxMinReg${k}-${n}-${pocetCasti}.txt
  rm $subor
done

echo "trvanie celeho spracovania je $SECONDS sekund" >> maxMinReg${k}-${n}-${pocetCasti}.txt
echo "trvanie celeho spracovania je $SECONDS sekund";
exit 0;