#!/bin/bash
SECONDS=0

pocetCasti=$1;
n=$2;
k=$3;

for i in $(eval echo {1..${pocetCasti}}); do
  GenReg $n $k -e -a stdout -m $i $pocetCasti | kostryTriedy out-graf-$i $n $k &
done

wait;
zberTriedy out-graf $pocetCasti $n $k;

eval rm out-graf-{1..${pocetCasti}};

for i in $(eval echo {1..${pocetCasti}}); do
  subor=${n}_${k}_3#${i}.erg
  cat $subor >> triedyKostier${k}-${n}-${pocetCasti}.txt
  rm $subor
done

echo "trvanie celeho spracovania je $SECONDS sekund" >> triedyKostier${k}-${n}-${pocetCasti}.txt
echo "trvanie celeho spracovania je $SECONDS sekund";
exit 0;