#!/bin/bash
SECONDS=0

if (($# != 3))
  then
    echo "Wrong number of arguments"
    exit 1
fi

n=$1;
k=$2;
g=$3;

if ! parametersCheck $n n
then 
    exit 1
fi

if ! parametersCheck $k k
then 
    exit 1
fi

if (($k >= $n))
  then
    echo "k can't be higher than n"
    exit 1
fi

if ! parametersCheck $g t
then 
    exit 1
fi

GenReg $n $k $g -e -a stdout | spanningTreesRegular $n $k;

file=${n}_${k}_${g}.erg;
if ((n < 10))
then
    file=0${n}_${k}_3.erg
fi

cat $file >> maxMinReg${k}-${n}.txt;
rm $file;

echo "trvanie celeho spracovania je $SECONDS sekund" >> maxMinReg${k}-${n}.txt
echo "trvanie celeho spracovania je $SECONDS sekund";

mv maxMinReg${k}-${n}.txt maxMinRegGirth${k}-${n}-${g}.txt;
exit 0;