#!/bin/bash
SECONDS=0

n=$1;
k=$2;

GenReg $n $k -e -a stdout | kostryTriedy $n $k;

file=${n}_${k}_3.erg;
cat $file >> triedyKostier${k}-${n}.txt;
rm $file;

echo "trvanie celeho spracovania je $SECONDS sekund" >> triedyKostier${k}-${n}.txt
echo "trvanie celeho spracovania je $SECONDS sekund";
exit 0;