#!/bin/bash
SECONDS=0

pocetCasti=$1;
n=$2;
k=$3;

for i in $(eval echo {1..${pocetCasti}}); do
  sh -c "GenReg $n $k -e -a stdout -m $i $pocetCasti | kostryRegularne out-graf-$i $n $k" &
done

wait;
zberRegularne out-graf $pocetCasti $n $k;

eval rm out-graf-{1..${pocetCasti}};

for i in $(eval echo {1..${pocetCasti}}); do
  subor=${n}_${k}_3#${i}.erg
  cat $subor >> maxMinReg${k}-${n}-${pocetCasti}.txt
  rm $subor
done

echo "trvanie celeho spracovania je $SECONDS sekund" >> maxMinReg${k}-${n}-${pocetCasti}.txt
echo "trvanie celeho spracovania je $SECONDS sekund";
exit 0;